#pragma once

#include <string>

enum HoverType {
    NO_HOVER,
    HOVER_SQUARE,
    HOVER_TOP,
    HOVER_LEFT,
    HOVER_RIGHT,
    HOVER_BOTTOM,
    HOVER_BR,
    HOVER_TR,
    HOVER_BL,
    HOVER_TL
};

enum PixelDelegateData {
    DRAW_BG1 = 32,
    DRAW_BG2 = 31,
    DRAW_BG3 = 30,

    PIXEL_ARRAY_BG2 = 101,
    PALETTE_ARRAY_BG2 = 102,
    TILEATTR_BG2 = 103,
    FLIP_H_BG2 = 104,
    FLIP_V_BG2 = 105,

    COLLISION_DRAW = 106,
    SHOW_COLLISION = 107,
    DEBUG_DATA = 108,

    PIXEL_ARRAY_BG1 = 109,
    PALETTE_ARRAY_BG1 = 110,
    TILEATTR_BG1 = 111,
    FLIP_H_BG1 = 112,
    FLIP_V_BG1 = 113,

    /**
     * Type: int
     * Purpose: Object ID to print out
     */
    OBJECT_ID = 114,
    OBJECT_PALETTE = 115,
    OBJECT_TILES = 116,
    OBJECT_UUID = 117,

    // BG3 support
    PIXEL_ARRAY_BG3 = 118,
    PALETTE_ARRAY_BG3 = 119,
    TILEATTR_BG3 = 120,
    FLIP_H_BG3 = 121,
    FLIP_V_BG3 = 122,

    DRAW_OBJECTS = 123,

    LAYER_DRAW_ORDER = 124,

    DRAW_TRIGGERS = 125,

    DRAW_TRANS_TILES = 126,
    TILE_ID_BG1 = 127,
    TILE_ID_BG2 = 128,
    TILE_ID_BG3 = 129,

    COLLISION_DEBUG = 130,
    HOVER_TYPE = 131,

    PALETTE_ID_BG1 = 132,
    PALETTE_ID_BG2 = 133,
    PALETTE_ID_BG3 = 134,

    TILE_SELECTED_BG1 = 135,
    TILE_SELECTED_BG2 = 136,
    TILE_SELECTED_BG3 = 137,
    SPRITE_SELECTED = 138
};

enum CollisionType {
    NONE = 0x0,
    SQUARE = 0x1,
    PLATFORM_PASSABLE = 0x2, // You can jump from below it and land on it, no head hit
    UP_RIGHT_30 = 0x3,
    UP_RIGHT_30_HALFSTART = 0x4,
    UP_RIGHT_STEEP_1 = 0x5,
    UP_RIGHT_STEEP_2 = 0x6,
    UP_RIGHT_45 = 0x7,
    STATIC_COIN = 0x1a,
    SOFT_ROCK = 0x1b,
    CLIMBABLE_VINE_CEILING = 0x1c,
    CLIMBABLE_VINE_TALL = 0x1d,
    DOWN_RIGHT_30_2 = 0x43,
    DOWN_RIGHT_30_1 = 0x44,
    DOWN_RIGHT_STEEP_HALFSTART = 0x45,
    DOWN_RIGHT_STEEP = 0x46,
    DOWN_RIGHT_45 = 0x47,
    BROWN_FLOATING_STAIRS_UP_LEFT = 0x5f,
    UPSIDE_DOWN_DOWNWARDS_45 = 0x87,
    UPSIDE_DOWN_UP_30 = 0xc4,
    UPSIDE_DOWN_UP_30_2 = 0xc3,
    UPSIDE_DOWN_UP_RIGHT = 0xc7
};

enum CollisionDraw {
    CLEAR,
    CORNER_TOP_RIGHT,
    CORNER_TOP_LEFT,
    CORNER_BOTTOM_LEFT,
    CORNER_BOTTOM_RIGHT,
    SQUARE_DRAW,
    ZIG_ZAG,
    DIAG_DOWN_RIGHT,
    DIAG_UP_RIGHT,
    COIN_TOP_LEFT,
    COIN_TOP_RIGHT,
    COIN_BOTTOM_LEFT,
    COIN_BOTTOM_RIGHT,
    UP_RIGHT_30_BL,
    UP_RIGHT_30_BR,
    UP_RIGHT_30_HALFSTART_UL,
    UP_RIGHT_30_HALFSTART_UR,

    DOWN_RIGHT_30_TALL,
    DOWN_RIGHT_30_SHORT,
    UPSIDE_DOWN_RIGHT_45,
    UPSIDE_DOWN_RIGHT_UP_30_TALL,
    UPSIDE_DOWN_RIGHT_UP_30_SHORT,

    UP_RIGHT_STEEP_TALL,
    UP_RIGHT_STEEP_SHORT,

    UPSIDE_DOWN_DOWNWARDS_45_DRAW,

    DOWN_RIGHT_STEEP_THIN,
    DOWN_RIGHT_STEEP_WIDE,
    SQERR
};

struct CollisionMetadata {
    CollisionType colType;
    CollisionDraw preview;
    std::string prettyName;
};